---
title: 'Measuring Quarterback’s value in passing efficiency change '
author: "Adrian Cadena"
date: '2020-11-22T21:13:14-05:00'
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  distill::distill_article:
    self_contained: no
    toc: yes
    toc_depth: 3
categories: R
description: |
  Revisiting my QB effect analysis.
repository_url: https://github.com/adriancm93/mixed_effects_bootstrapping
tags:
- R
- Mixed-Effects
- Bootstrapping
- NFL
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = FALSE, 
  dpi = 700, 
  tidy = 'styler',
  fig.width=7
  )
```


# Description

Revisiting my project evaluating QB impact.

# Plotting

```{r}
library(ggplot2)
qb <- data.frame(coef = readRDS('passer1.rds'),effect='QB')
team <- data.frame(coef = readRDS('team1.rds'),effect='Team')
coach <- data.frame(coef = readRDS('poscoach1.rds'),effect='Coach')
defteam <- data.frame(coef = readRDS('defteam1.rds'),effect='DefTeam')
defcoach <- data.frame(coef = readRDS('defcoach1.rds'),effect='DefCoach')

plot2 <- rbind(qb,team,coach,defteam,defcoach)

ggplot(plot2,aes(x=coef,fill=effect))+
  geom_density(alpha=.4)+
  theme_bw()+ 
  labs(x='Coefficient', y='Density')
```

